### ISSUE TITLE
400 bad request on routes except telemetryPath

### ISSUE THREAD

**Issue by booooza** [flownative/flow-prometheus#2]
Hello

First of all great effort to integrate prometheus into flow, thanks for that! 

After setting the environment variable `FLOWNATIVE_PROMETHEUS_ENABLE` to `true` there is a `400 bad request` on all app routes except `telemetryPath` (e.g. /metrics). Based on the readme this seems like a design decision and the idea is that the environment variable `FLOWNATIVE_PROMETHEUS_ENABLE` is set e.g. per virtual host on the web server.

On a cloud environment this can be an issue as there might be no easy way to differentiate the environment variables per path, in this case setting it only for the `telemetryPath`. Is there maybe another way to use the package on the same host as the application (same environment variables)?

Kind Regards

**Comment by kitsunet** [comment]
Actually we made it for cloud usage just like that. How we use it is to expose the application with another port that is only accessible by prometheus internally and provide the environment variable to php-fpm only when accessed via that port and not via the normal web exposed port. I guess we can discuss alternative solutions if you have any ideas?

**Comment by booooza** [comment]
Totally understand the point from security perspective and will have to solve that as well in our case. However protecting the metrics endpoint via different ports might not be the only way to achieve it (could also be reverse proxies, ingress rules on a WAF or no protection at all). The method with different ports could be a bit of an issue in cloud environments with high abstraction (such as PaaS) as you might not always can or want to deal with web server configurations or run the same web application on multiple ports.

**Comment by kaystrobach** [comment]
Just checked it out and found it irritating.

my suggestion is to patch the MetricsExporterComponent like this:

```
    /**
     * @param ComponentContext $componentContext
     */
    public function handle(ComponentContext $componentContext): void
    {
        if (getenv('FLOWNATIVE_PROMETHEUS_ENABLE') !== 'true') {
            return;
        }
        
        if ($componentContext->getHttpRequest()->getUri()->getPath() !== $this->options['telemetryPath']) {
            return;
        }

        $componentContext->setParameter(ComponentChain::class, 'cancel', true);

        if ($this->options['basicAuth']['username'] !== '' && $this->options['basicAuth']['password'] !== '') {
            if ($this->authenticateWithBasicAuth($componentContext) === false) {
                $response = $this->createResponseWithAuthenticateHeader($componentContext->getHttpResponse());
                $componentContext->replaceHttpResponse($response);
                return;
            }
        }

        $response = $this->createResponseWithRenderedMetrics($componentContext->getHttpResponse());
        $componentContext->replaceHttpResponse($response);
    }
```

That way we have an early exit if the env var is not correct (current behaviour), and we have the options to use it together with prodction on the same uri.

What's your opinion @kitsunet ?

**Comment by robertlemke** [comment]
Thanks for the suggestion – I think it makes sense, so I implemented it as requested. Please let me know if it didn't work for you as expected.

**Comment by kaystrobach** [comment]
Will check it out.
