### ISSUE TITLE
What do i have to do to see metrics from `Flownative.Prometheus.FlowMetrics`

### ISSUE THREAD

**Issue by kaystrobach** [flownative/flow-prometheus#3]
Steps to reproduce:

Packages

```
neos/flow                               5.3.21             Flow Application Framework
flownative/prometheus                   0.7.0              Prometheus metrics for Neos Flow applications
flownative/prometheus-flow-metrics      0.2.2              Prometheus metrics for Neos Flow applications
...
```

If i get it right, the prometheus-flow-metrics should provide 2 metrics:

1. Number of requests - makes no sense for me
2. Number of sessions - makes total sense

Is:

* The HttpMetricsCollector is called - no output.
* The SessionMetricsCollectorService is not called.

Expectation:

* Both metrics are exposed

Output

```
# Flownative Prometheus Metrics Exporter: There are currently no metrics with data to  export.
```

It seems to me, that the samples are empty:

```
Packages/Application/Flownative.Prometheus/Classes/Renderer.php:36

\Flownative\Prometheus\Renderer::render
```

Any idea?

**Comment by kaystrobach** [comment]
PS: I just installed the 2 packages and applied the patch from #2 (but the output was the same before).

Esp. for the sessions i would also expect an output of 0 instead of nothing.

**Comment by robertlemke** [comment]
You should actually see something like this, even if there are no active sessions:

```
# HELP neos_flow_http_requests_total Number of HTTP requests processed by Flow's HTTP stack
# TYPE neos_flow_http_requests_total counter
neos_flow_http_requests_total{status="200"} 23
neos_flow_http_requests_total{status="201"} 1
neos_flow_http_requests_total{status="303"} 88
neos_flow_http_requests_total{status="403"} 3

# HELP neos_flow_sessions Number of Flow sessions
# TYPE neos_flow_sessions gauge
neos_flow_sessions{state="active"} 0
```

I [just pushed a little change](https://github.com/flownative/flow-prometheus/commit/ba468c88271bc5b7a177d3222175be5e8f685462) which gives you a hint in the metrics comment if there are actually no collectors registered or if there are collectors, but without data.

If that doesn't help, I guess you need to add some var_dumps here and there to see where things go wrong.

**Comment by kaystrobach** [comment]
Mhmm ok - i think i get the point.

I tried to use the InMemoryCollector.
The Problem is that the collector is not executed when the /metrics endpoint is called - just parts of the framework are loaded.

```
class Package extends BasePackage
{
    /**
     * @param Bootstrap $bootstrap
     */
    public function boot(Bootstrap $bootstrap): void
    {
        $dispatcher = $bootstrap->getSignalSlotDispatcher();
        $dispatcher->connect(Bootstrap::class, 'finishedRuntimeRun', SessionMetricsCollectorService::class, 'collect');
    }
}
```

The above code gets executed all the time during a normal run - therefore it works for redis.

It's never executed during a call to  `/metrics` so that it can not display the number of active sessions at this point in time.
IMHO the example is misleading.

Steps to reproduce:

```
neos/flow 5.3.21
flownative/prometheus                   dev-master ba468c8 Prometheus metrics for Neos Flow applications
flownative/prometheus-flow-metrics      dev-master 0a3badc Prometheus metrics for Neos Flow applications
```

Output:

```
# Flownative Prometheus Metrics Exporter: There are currently no metrics with data to export.
```

The question is, if it's not better to emit a signal from the `handle` function of the MetricsExporterComponent?

`Packages/Application/Flownative.Prometheus/Classes/Http/MetricsExporterComponent.php:76`

That point in the code is always reached and also executed - only possible problem might be, that it's to early in the process flow for some metrics like response time ... mhmm.

**Comment by kaystrobach** [comment]
Without touching the code i would do the following:
Settings.yaml
```yaml
Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'Flownative.Prometheus:metricsProvider':
              'position': 'before Flownative.Prometheus:metricsExporter'
              component: 'Flownative\Prometheus\FlowMetrics\Http\MetricsProviderComponent'
```

and the class just looks like that:

```php
<?php

namespace Flownative\Prometheus\FlowMetrics\Http;


use Flownative\Prometheus\FlowMetrics\SessionMetricsCollectorService;
use Neos\Flow\Http\Component\ComponentContext;
use Neos\Flow\Http\Component\ComponentInterface;

/**
 * HTTP component which renders Prometheus metrics
 */
class MetricsProviderComponent implements ComponentInterface
{
    /**
     * @param ComponentContext $componentContext
     */
    public function handle(ComponentContext $componentContext): void
    {
        $smcs = new SessionMetricsCollectorService();
        $smcs->collect();
    }
}
```

That code provided the expected output:

```prometheus
# HELP neos_flow_sessions Number of Flow sessions
# TYPE neos_flow_sessions gauge
neos_flow_sessions{state="active"} 10
```

Maybe it makes sense to switch to this approach to ensure metrics get always collected properly? - What's you opinion?

**Comment by robertlemke** [comment]
If I understand you correctly, I think you're approaching it contrary to the Prometheus best practices. The README of this package states:

> The metrics endpoint (by default http(s)://your-host/metrics) collects
all current metric values from the storage and renders it in a format
which can be read by Prometheus. Therefore, metrics are _not_ collected
or generated during a request to the metrics endpoint.

That's important. Metrics must be collected separately and not be triggered by some service fetching them via the telemetry endpoint. So, calling https://example.com/metrics and by that triggering a collection of the session metrics would be wrong.

The actual implementation depends on the metric you are trying to support. But most certainly, very few metrics will work with the InMemoryStorage.

**Comment by kaystrobach** [comment]
But for what reason do we have the in memory storage then?

i thought i can simply poll the DB / redis during the metrics run (as it’s mostly counting)

this would also lower the impact for as the metrics are not updated during each and every request but once they are needed - which is only the metrics endpoint.

**Comment by robertlemke** [comment]
> But for what reason do we have the in memory storage then?

For testing and development. As the README states:

> By default, this plugin uses the InMemoryStorage for testing purposes. You will want to use the RedisStorage instead, so you don't loose all metrics values between requests.

**Comment by kaystrobach** [comment]
Ok - will do a PR then, which makes it clear in the inMemory storage.
